# Useful Functions
source "$ZDOTDIR/zsh_functions"

# Plugins
yazp_init
yazp plug "zsh-users/zsh-autosuggestions"
yazp plug "zsh-users/zsh-syntax-highlighting"
yazp plug "hlissner/zsh-autopair"
yazp plug "asdf-vm/asdf" "asdf.sh" # actually this is not zsh plugin
yazp plug "zsh-users/zsh-completions"
yazp theme "ucchiee/pure" "zsh_pure"
# For more plugins: https://github.com/unixorn/awesome-zsh-plugins
# More completions https://github.com/zsh-users/zsh-completions

# Files to source
zsh_add_file "zsh_exports"
# zsh_add_file "zsh_vim_mode"
zsh_add_file "zsh_aliases"
zsh_add_file "zsh_comp"
zsh_add_file "zsh_general"
zsh_add_file "zsh_keybind"
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Hook direnv into your shell.
# eval "$(asdf exec direnv hook zsh)"
# A shortcut for asdf managed direnv.
# direnv() { asdf exec direnv "$@"; }
