#!/bin/sh
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"

# alias for ls
alias sl='ls'
alias l='ls -ltrG'
alias la='ls -lhaG'
alias ll='ls -lhG'
case "$(uname -s)" in
 Darwin)
   # echo 'Mac OS X'
  alias ls='ls -G'
   ;;
 Linux)
  alias ls='ls --color=auto'
   ;;

 CYGWIN*|MINGW32*|MSYS*|MINGW*)
   # echo 'MS Windows'
   ;;
 *)
   # echo 'Other OS'
   ;;
esac

# alias for cd
alias ...='cd ../../'
alias f='cd ~/Code'
alias j='cd ~/Documents/TokyoTech/jk4/1q'
alias k='cd ~/Documents/TokyoTech/DeepLab/workspace'

# alias for git
alias gi='git init'
alias pc='pre-commit install&&cp $DOTFILES_DIR/.pre-commit-config.yaml .'
alias ga='git add'
alias gc='git commit'
alias gps='git push'
alias gpl='git pull'
alias gck='git checkout'
alias gs='git branch;git status'
alias gb='git branch'
alias gd='git diff'
alias g='git'
alias gt='git tree'
alias gcl='git clone'
alias gm='git merge'

# alias for tools
alias v='vim'
alias vv='vim -u NONE -N'
alias sv='vim -u $DOTFILES_DIR/simple.vimrc -N'
alias n='nvim'
alias n.='n .'
alias nn='nvim-nighty'
alias vn='nvim -u NONE -N'
alias sn='nvim -u $DOTFILES_DIR/simple.vimrc -N'
alias t='tmux'
alias lg='lazygit'
alias gl='lazygit'
alias ldk='lazydocker'  # "ld" overwrite ld command.
alias dl='lazydocker'
alias jq.='jq .'

# alias for alacritty
export CURRENT_FONT_SIZE=15.
alias reset_font='sed -i "" "s/size: .../size: 15./g" ~/.config/alacritty/alacritty.yml&&export CURRENT_FONT_SIZE=15.'
alias smaller=' sed -i "" "s/size: $CURRENT_FONT_SIZE/size: $(($CURRENT_FONT_SIZE - 3.0))/g" ~/.config/alacritty/alacritty.yml&&export CURRENT_FONT_SIZE=$(($CURRENT_FONT_SIZE - 3))'
alias bigger=' sed -i "" "s/size: $CURRENT_FONT_SIZE/size: $(($CURRENT_FONT_SIZE + 3.0))/g" ~/.config/alacritty/alacritty.yml&&export CURRENT_FONT_SIZE=$(($CURRENT_FONT_SIZE + 3))'

# alias for zsh
alias zshtime='for for i in $(seq 1 10); do time zsh -i -c exit; done'
alias init='source $ZDOTDIR/zsh_env_lazy'

# other useful alias
alias grep='grep --color=auto'
alias G='grep'
alias his='history -E -i 1 | fzf'
alias jn='jupyter notebook'
alias jl='jupyter lab'
alias c='clear'
alias ggl='open -a google\ chrome'
alias jk='ssh -ND 1080 titech-computing-room'
alias jkjk='ssh titech-computing-room'
