# Useful Functions
source $ZDOTDIR/zsh-functions

# Source files
zsh_add_file "zsh_exports"
zsh_add_file "zsh_aliases"
zsh_add_file "zsh_theme"
zsh_add_file "zsh_comp"
zsh_add_file "zsh_optns"
# You can source .zsh_env_lazy by "init" alias
# zsh_add_file "zsh_env_lazy"

# Plugin
zsh_add_plugin "zsh-users/zsh-autosuggestions"
zsh_add_plugin "zsh-users/zsh-syntax-highlighting"
