autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search

# Useful Functions
source $ZDOTDIR/zsh_functions

# Plugin
zsh_add_plugin "zsh-users/zsh-autosuggestions"
zsh_add_plugin "zsh-users/zsh-syntax-highlighting"
zsh_add_plugin "hlissner/zsh-autopair"
zsh_add_plugin "asdf-vm/asdf"
zsh_add_theme "sindresorhus/pure" "zsh_pure"
# zsh_add_theme "romkatv/powerlevel10k" ""
# zsh_add_theme "reobin/typewritten" ""
# zsh_add_theme "spaceship-prompt/spaceship-prompt" ""
# For more plugins: https://github.com/unixorn/awesome-zsh-plugins
# More completions https://github.com/zsh-users/zsh-completions

# Files to source
zsh_add_file "zsh_exports"
# zsh_add_file "zsh_vim_mode"
zsh_add_file "zsh_aliases"
zsh_add_file "zsh_comp"
zsh_add_file "zsh_optns"
zsh_add_file "$HOME/.fzf.zsh"

# Keybinding
bindkey -s '^o' 'ranger^M'
# bindkey -s '^f' 'zi^M'
bindkey -s '^@' 'ncdu^M'
bindkey "^p" up-line-or-beginning-search # Up
bindkey "^k" up-line-or-beginning-search # Up
bindkey "^n" down-line-or-beginning-search # Down
bindkey "^j" down-line-or-beginning-search # Down
# bindkey -r "^u"
# bindkey -r "^d"
#
# Use vim keys in tab complete menu:
zmodload zsh/complist
bindkey -M menuselect '^h' vi-backward-char
bindkey -M menuselect '^k' vi-up-line-or-history
bindkey -M menuselect '^l' vi-forward-char
bindkey -M menuselect '^j' vi-down-line-or-history
